version: "3.8"

services:
  client:
    container_name: client
    build:
      context: client
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
  server:
    container_name: server
    build:
      context: server
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - 5000:5000
    environment:
      - DB_CONNECTION_URI=mongodb://admin:password@db:27017/enroute?retryWrites=true&w=majority&appName=AtlasApp
      - PORT=5000
    volumes:
      - ./server:/app
  db:
    container_name: db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: enroute
    ports:
      - 27017:27017
    volumes:
      - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - db-data:/data/db

volumes:
  db-data:
