db.createUser({ user: "admin", pwd: "password", roles: ["dbOwner"] });

db.createCollection("electronicColorCodes");
db.electronicColorCodes.insertMany([
  {
    name: "None",
    colorHex: "#F8F9FA",
    multiplier: 0,
    tolerancePercent: 20,
    toleranceLetter: "M",
  },
  {
    name: "Pink",
    colorHex: "#D8A0A6",
    code: "PK",
    ral: 3015,
    multiplier: 0.001,
  },
  {
    name: "Silver",
    colorHex: "#C0C0C0",
    code: "SR",
    multiplier: 0.01,
    tolerancePercent: 10,
    toleranceLetter: "K",
  },
  {
    name: "Gold",
    colorHex: "#FFD700",
    code: "GD",
    multiplier: 0.1,
    tolerancePercent: 5,
    toleranceLetter: "J",
  },
  {
    name: "Black",
    colorHex: "#0E0E10",
    code: "BK",
    ral: 9005,
    significantFigure: 0,
    multiplier: 1,
    temperatureCoefficient: 250,
    temperatureLetter: "U",
  },
  {
    name: "Brown",
    colorHex: "#7E4B26",
    code: "BN",
    ral: 8003,
    significantFigure: 1,
    multiplier: 10,
    tolerancePercent: 1,
    toleranceLetter: "F",
    temperatureCoefficient: 100,
    temperatureLetter: "S",
  },
  {
    name: "Red",
    colorHex: "#A72920",
    code: "RD",
    ral: 3000,
    significantFigure: 2,
    multiplier: 100,
    tolerancePercent: 2,
    toleranceLetter: "G",
    temperatureCoefficient: 50,
    temperatureLetter: "R",
  },
  {
    name: "Orange",
    colorHex: "#F67828",
    code: "OG",
    ral: 2003,
    significantFigure: 3,
    multiplier: 1000,
    tolerancePercent: 0.05,
    toleranceLetter: "W",
    temperatureCoefficient: 15,
    temperatureLetter: "P",
  },
  {
    name: "Yellow",
    colorHex: "#F6B600",
    code: "YE",
    ral: 1021,
    significantFigure: 4,
    multiplier: 10000,
    tolerancePercent: 0.02,
    toleranceLetter: "P",
    temperatureCoefficient: 25,
    temperatureLetter: "Q",
  },
  {
    name: "Green",
    colorHex: "#61993B",
    code: "GN",
    ral: 6018,
    significantFigure: 5,
    multiplier: 100000,
    tolerancePercent: 0.5,
    toleranceLetter: "D",
    temperatureCoefficient: 20,
    temperatureLetter: "Z",
  },
  {
    name: "Blue",
    colorHex: "#007CB0",
    code: "BU",
    ral: 5015,
    significantFigure: 6,
    multiplier: 1000000,
    tolerancePercent: 0.25,
    toleranceLetter: "C",
    temperatureCoefficient: 10,
    temperatureLetter: "Z",
  },
  {
    name: "Violet",
    colorHex: "#76689A",
    code: "VT",
    ral: 4005,
    significantFigure: 7,
    multiplier: 10000000,
    tolerancePercent: 0.1,
    toleranceLetter: "B",
    temperatureCoefficient: 5,
    temperatureLetter: "M",
  },
  {
    name: "Gray",
    colorHex: "#7A888E",
    code: "GY",
    ral: 7000,
    significantFigure: 8,
    multiplier: 100000000,
    tolerancePercent: 0.01,
    toleranceLetter: "L (A)",
    temperatureCoefficient: 1,
    temperatureLetter: "K",
  },
  {
    name: "White",
    colorHex: "#e3d9c6",
    code: "WH",
    ral: 1013,
    significantFigure: 9,
    multiplier: 1000000000,
  },
]);
