import { EColor } from "../../shared/enums/color.enum";
import zod from "zod";

export const calculate4BandsSchema = zod.object({
  bandAColor: zod.enum([
    EColor.BLACK,
    EColor.BROWN,
    EColor.RED,
    EColor.ORANGE,
    EColor.YELLOW,
    EColor.GREEN,
    EColor.BLUE,
    EColor.VIOLET,
    EColor.GRAY,
    EColor.WHITE,
  ]),
  bandBColor: zod.enum([
    EColor.BLACK,
    EColor.BROWN,
    EColor.RED,
    EColor.ORANGE,
    EColor.YELLOW,
    EColor.GREEN,
    EColor.BLUE,
    EColor.VIOLET,
    EColor.GRAY,
    EColor.WHITE,
  ]),
  bandCColor: zod.enum([
    EColor.PINK,
    EColor.SILVER,
    EColor.GOLD,
    EColor.BLACK,
    EColor.BROWN,
    EColor.RED,
    EColor.ORANGE,
    EColor.YELLOW,
    EColor.GREEN,
    EColor.BLUE,
    EColor.VIOLET,
    EColor.GRAY,
    EColor.WHITE,
  ]),
  bandDColor: zod.enum([
    EColor.NONE,
    EColor.SILVER,
    EColor.GOLD,
    EColor.BROWN,
    EColor.RED,
    EColor.ORANGE,
    EColor.YELLOW,
    EColor.GREEN,
    EColor.BLUE,
    EColor.VIOLET,
    EColor.GRAY,
  ]),
});
